# Terraform CD pipeline template

parameters:
  # unique name of the job
  job_name: deploy_terraform
  # friendly name of the job
  display_name: Deploy app components with Terraform
  # directory of main.tf (mandatory)
  terraform_working_dir: ''
  # name of target enviroment deploying to (mandatory)
  target_environment: ''
  # name of variable group = target enviroment (manadatory)
  variable_group_name: ''
  # Azure subscription
  azure_subscription: 'Free Trial(4cc37679-12d4-439a-99cf-6072b19a3fee)'

jobs:
- deployment: ${{ parameters.job_name }}
  displayName: ${{ parameters.display_name }}
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.target_environment }}
  variables:
  - group: ${{parameters.variable_group_name}} # (list the necessary variables to be set here)
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none
        - download: current
          artifact: drop
          patterns: '**/*.zip'
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: '0.12.20'
        - task: TerraformCLI@0
          display_name: terraform init
          inputs:
            command: 'init'
            workingDirectory: '${{ parameters.terraform_working_dir }}'
            commandOptions: '-backend-config=resource_group_name=$(RES_GRP) -backend-config=storage_account_name=$(STORAGE_ACCT) -backend-config=container_name=tf-statefiles -backend-config=key=$(state.key) -backend-config=access_key=$(ACCESS_KEY) -no-color -input=false'
            backendType: 'azurerm'
        - task: TerraformCLI@0
          display_name: terraform validate
          inputs:
            workingDirectory: '${{ parameters.terraform_working_dir }}'
            command: 'validate'
            commandOptions: '-check-variables=false'
        - task: TerraformCLI@0
          display_name: terraform plan
          inputs:
            workingDirectory: '${{ parameters.terraform_working_dir }}'
            command: 'plan'
            environmentServiceName: 'Free Trial(4cc37679-12d4-439a-99cf-6072b19a3fee)'
            commandOptions: '-out=tfplan -no-color -input=false -detailed-exitcode'
              workingDirectory: ''$(terraform.path)'
        - task: ManualIntervention@8
          display_name: terraform manual review
          condition: 'and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))'
          inputs:
            instructions: 'Please review the Terraform preview in the pipeline logs and click Continue to approve.'
            emailRecipients: 'sten.rosendahl@alfalaval.com'
        - task: TerraformCLI@0
          display_name: terraform apply
          inputs:
            command: 'apply'
            environmentServiceName: 'Free Trial(4cc37679-12d4-439a-99cf-6072b19a3fee)'
            commandOptions: '-input=false -auto-approve=true -lock=true'
