# Sample of multi-stage CD pipeline using YAML template and Terraform plugin for deployment
variables:
  appName: 'SpaceGameWeb'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'deploytest'
  displayName: Deploy to test
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
    - template: ./azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_to_test
        display_name: Deploy $(appName) to test environment
        build_branch: 'develop'
        variable_group_name: test_configuration

- stage: 'deploypreprod'
  displayName: Deploy to preprod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: ./azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_to_preprod
        display_name: Deploy $(appName) to preprod environment
        build_branch: 'master'
        variable_group_name: preprod_configuration

- stage: 'deployprod'
  displayName: Deploy to prod
  dependsOn: 'deploypreprod'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - template: ./azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_to_prod
        display_name: Deploy $(appName) to prod environment
        build_branch: 'master'
        variable_group_name: prod_configuration
