trigger:
- none

  stage: Dev  
    jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      pool:
        vmImage: 'Ubuntu-16.04'
      # Records deployment against bookings resource - Kubernetes namespace.
      environment: 'Dev'
      strategy: 
        runOnce:
          deploy:
            steps:
