# Sample of multi-stage CD pipeline using YAML template and Terraform plugin for deployment
variables:
  appName: 'SpaceGameWeb'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'tfplandev'
  displayName: Terraform plan for dev environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
    - template: ./azure-pipelines-deploy-plan-template.yml
      parameters:
        job_name: tf_plan_to_dev
        display_name: Terraform plan $(appName) to dev environment
        build_branch: 'develop'
        variable_group_name: dev_configuration
- stage: 'tfapplydev'
  displayName: Apply terraform to dev
  dependsOn: tfplandev
  jobs:
    - template: ./azure-pipelines-deploy-apply-template.yml
      parameters:
        job_name: apply_to_dev
        display_name: Deploy $(appName) to dev environment
        build_branch: 'develop'
        variable_group_name: dev_configuration
