# Sample of multi-stage CD pipeline using YAML template and Terraform plugin for deployment

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: deploytest'
  displayName: Deploy to test
  jobs:
    - template: ./azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_solution_to_test
        target_environment: 'test'
        variable_group_name: test_configuration
- stage: 'deploypreprod'
  dependsOn: 'deploytest'
  jobs:
    - template: ./templates/azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_solution_to_preprod
        target_environment: 'preprod'
        variable_group_name: preprod_configuration
